import Header from '@/components/header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    template: '%s | Boiler',
    default: 'Acme',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </header>
        <main>
          <div className="w-full h-screen">
            <Header />
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
